In [228]:
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from PIL import Image
import numpy as np

In [229]:
pyLogo = Image.open("../figures/nhl_rink.png").convert("RGB")
fig = px.imshow(pyLogo)

fig.update_layout(yaxis_title="", # TODO
                  xaxis_title="") # TODO


# Set templates
fig.update_layout(template="plotly_white")
fig.show()

In [230]:
df = pd.read_csv('../datasets/tidy_data.csv')

In [231]:
df_20162017 = df[df["season"]==20162017]
len(df_20162017)

80399

In [242]:
df_question_2 = df_20162017.groupby(['x_coord','y_coord'])['x_coord'].count().reset_index(name="count")

In [243]:
df_question_2["count"].sort_values()

5709       1
5450       1
5452       1
5453       1
5454       1
        ...
832       86
836       87
684       89
10644     90
834      100
Name: count, Length: 11420, dtype: int64

In [244]:
df_question_2["mean_shots_per_hour_in_whole_league"] = df_question_2["count"]/df_20162017["id_game"].nunique()

In [245]:
df_question_2.head(5)

   x_coord  y_coord  count  mean_shots_per_hour_in_whole_league
0    -98.0      9.0      2                             0.001519
1    -98.0     15.0      1                             0.000759
2    -97.0    -18.0      2                             0.001519
3    -97.0    -10.0      1                             0.000759
4    -97.0     16.0      1                             0.000759

In [250]:
#df_20162017.groupby(['name_team_that_shot'])
df_20162017.groupby(['x_coord','y_coord','name_team_that_shot']).count()

                                     event_Idx  periodTime  id_team_that_shot  \
x_coord y_coord name_team_that_shot
-98.0    9.0    Los Angeles Kings            2           2                  2
         15.0   Anaheim Ducks                1           1                  1
-97.0   -18.0   Dallas Stars                 1           1                  1
                Minnesota Wild               1           1                  1
        -10.0   New Jersey Devils            1           1                  1
...                                        ...         ...                ...
 97.0   -8.0    New York Rangers             1           1                  1
        -7.0    Nashville Predators          1           1                  1
         7.0    Edmonton Oilers              1           1                  1
         10.0   New York Rangers             1           1                  1
 98.0   -3.0    Detroit Red Wings            1           1                  1

                                     result_event  goalie_name  shooter_name  \
x_coord y_coord name_team_that_shot
-98.0    9.0    Los Angeles Kings               2            2             2
         15.0   Anaheim Ducks                   1            1             1
-97.0   -18.0   Dallas Stars                    1            1             1
                Minnesota Wild                  1            1             1
        -10.0   New Jersey Devils               1            1             1
...                                           ...          ...           ...
 97.0   -8.0    New York Rangers                1            1             1
        -7.0    Nashville Predators             1            1             1
         7.0    Edmonton Oilers                 1            1             1
         10.0   New York Rangers                1            1             1
 98.0   -3.0    Detroit Red Wings               1            1             1

                                     shot_type  empty_net  strength  \
x_coord y_coord name_team_that_shot
-98.0    9.0    Los Angeles Kings            2          1         0
         15.0   Anaheim Ducks                1          0         0
-97.0   -18.0   Dallas Stars                 1          0         0
                Minnesota Wild               1          1         0
        -10.0   New Jersey Devils            1          0         0
...                                        ...        ...       ...
 97.0   -8.0    New York Rangers             1          0         0
        -7.0    Nashville Predators          1          0         0
         7.0    Edmonton Oilers              1          1         0
         10.0   New York Rangers             1          1         0
 98.0   -3.0    Detroit Red Wings            1          1         0

                                     type_season  id_game  season  dateTime  \
x_coord y_coord name_team_that_shot
-98.0    9.0    Los Angeles Kings              2        2       2         2
         15.0   Anaheim Ducks                  1        1       1         1
-97.0   -18.0   Dallas Stars                   1        1       1         1
                Minnesota Wild                 1        1       1         1
        -10.0   New Jersey Devils              1        1       1         1
...                                          ...      ...     ...       ...
 97.0   -8.0    New York Rangers               1        1       1         1
        -7.0    Nashville Predators            1        1       1         1
         7.0    Edmonton Oilers                1        1       1         1
         10.0   New York Rangers               1        1       1         1
 98.0   -3.0    Detroit Red Wings              1        1       1         1

                                     endDateTime  abstractGameState  \
x_coord y_coord name_team_that_shot
-98.0    9.0    Los Angeles Kings              2                  2
         15.0   Anaheim Ducks                  1                  1
-97.0   -18.0   Dallas Stars                   1                  1
                Minnesota Wild                 1                  1
        -10.0   New Jersey Devils              1                  1
...                                          ...                ...
 97.0   -8.0    New York Rangers               1                  1
        -7.0    Nashville Predators            1                  1
         7.0    Edmonton Oilers                1                  1
         10.0   New York Rangers               1                  1
 98.0   -3.0    Detroit Red Wings              1                  1

                                     team_away_name  team_home_name
x_coord y_coord name_team_that_shot
-98.0    9.0    Los Angeles Kings                 2               2
         15.0   Anaheim Ducks                     1               1
-97.0   -18.0   Dallas Stars                      1               1
                Minnesota Wild                    1               1
        -10.0   New Jersey Devils                 1               1
...                                             ...             ...
 97.0   -8.0    New York Rangers                  1               1
        -7.0    Nashville Predators               1               1
         7.0    Edmonton Oilers                   1               1
         10.0   New York Rangers                  1               1
 98.0   -3.0    Detroit Red Wings                 1               1

[64331 rows x 17 columns]

In [251]:
df_question_3 = df_20162017.groupby(['x_coord','y_coord','name_team_that_shot'])['name_team_that_shot'].count().reset_index(name="count_per_team")
df_question_3.head(5)

   x_coord  y_coord name_team_that_shot  count_per_team
0    -98.0      9.0   Los Angeles Kings               2
1    -98.0     15.0       Anaheim Ducks               1
2    -97.0    -18.0        Dallas Stars               1
3    -97.0    -18.0      Minnesota Wild               1
4    -97.0    -10.0   New Jersey Devils               1

In [252]:
df_question_3_p = df_question_3.pivot(index=["x_coord","y_coord"], columns="name_team_that_shot", values="count_per_team")
df_question_3_p.head(5)

name_team_that_shot  Anaheim Ducks  Arizona Coyotes  Boston Bruins  \
x_coord y_coord
-98.0    9.0                   NaN              NaN            NaN
         15.0                  1.0              NaN            NaN
-97.0   -18.0                  NaN              NaN            NaN
        -10.0                  NaN              NaN            NaN
         16.0                  NaN              NaN            NaN

name_team_that_shot  Buffalo Sabres  Calgary Flames  Carolina Hurricanes  \
x_coord y_coord
-98.0    9.0                    NaN             NaN                  NaN
         15.0                   NaN             NaN                  NaN
-97.0   -18.0                   NaN             NaN                  NaN
        -10.0                   NaN             NaN                  NaN
         16.0                   NaN             NaN                  NaN

name_team_that_shot  Chicago Blackhawks  Colorado Avalanche  \
x_coord y_coord
-98.0    9.0                        NaN                 NaN
         15.0                       NaN                 NaN
-97.0   -18.0                       NaN                 NaN
        -10.0                       NaN                 NaN
         16.0                       NaN                 NaN

name_team_that_shot  Columbus Blue Jackets  Dallas Stars  ...  \
x_coord y_coord                                           ...
-98.0    9.0                           NaN           NaN  ...
         15.0                          NaN           NaN  ...
-97.0   -18.0                          NaN           1.0  ...
        -10.0                          NaN           NaN  ...
         16.0                          NaN           NaN  ...

name_team_that_shot  Ottawa Senators  Philadelphia Flyers  \
x_coord y_coord
-98.0    9.0                     NaN                  NaN
         15.0                    NaN                  NaN
-97.0   -18.0                    NaN                  NaN
        -10.0                    NaN                  NaN
         16.0                    NaN                  NaN

name_team_that_shot  Pittsburgh Penguins  San Jose Sharks  St. Louis Blues  \
x_coord y_coord
-98.0    9.0                         NaN              NaN              NaN
         15.0                        NaN              NaN              NaN
-97.0   -18.0                        NaN              NaN              NaN
        -10.0                        NaN              NaN              NaN
         16.0                        NaN              NaN              NaN

name_team_that_shot  Tampa Bay Lightning  Toronto Maple Leafs  \
x_coord y_coord
-98.0    9.0                         NaN                  NaN
         15.0                        NaN                  NaN
-97.0   -18.0                        NaN                  NaN
        -10.0                        NaN                  NaN
         16.0                        1.0                  NaN

name_team_that_shot  Vancouver Canucks  Washington Capitals  Winnipeg Jets
x_coord y_coord
-98.0    9.0                       NaN                  NaN            NaN
         15.0                      NaN                  NaN            NaN
-97.0   -18.0                      NaN                  NaN            NaN
        -10.0                      NaN                  NaN            NaN
         16.0                      NaN                  NaN            NaN

[5 rows x 30 columns]

In [253]:
df_question_3_p[df_question_3_p.isna()]=0

In [254]:
df_question_3_p.head(5)

name_team_that_shot  Anaheim Ducks  Arizona Coyotes  Boston Bruins  \
x_coord y_coord
-98.0    9.0                   0.0              0.0            0.0
         15.0                  1.0              0.0            0.0
-97.0   -18.0                  0.0              0.0            0.0
        -10.0                  0.0              0.0            0.0
         16.0                  0.0              0.0            0.0

name_team_that_shot  Buffalo Sabres  Calgary Flames  Carolina Hurricanes  \
x_coord y_coord
-98.0    9.0                    0.0             0.0                  0.0
         15.0                   0.0             0.0                  0.0
-97.0   -18.0                   0.0             0.0                  0.0
        -10.0                   0.0             0.0                  0.0
         16.0                   0.0             0.0                  0.0

name_team_that_shot  Chicago Blackhawks  Colorado Avalanche  \
x_coord y_coord
-98.0    9.0                        0.0                 0.0
         15.0                       0.0                 0.0
-97.0   -18.0                       0.0                 0.0
        -10.0                       0.0                 0.0
         16.0                       0.0                 0.0

name_team_that_shot  Columbus Blue Jackets  Dallas Stars  ...  \
x_coord y_coord                                           ...
-98.0    9.0                           0.0           0.0  ...
         15.0                          0.0           0.0  ...
-97.0   -18.0                          0.0           1.0  ...
        -10.0                          0.0           0.0  ...
         16.0                          0.0           0.0  ...

name_team_that_shot  Ottawa Senators  Philadelphia Flyers  \
x_coord y_coord
-98.0    9.0                     0.0                  0.0
         15.0                    0.0                  0.0
-97.0   -18.0                    0.0                  0.0
        -10.0                    0.0                  0.0
         16.0                    0.0                  0.0

name_team_that_shot  Pittsburgh Penguins  San Jose Sharks  St. Louis Blues  \
x_coord y_coord
-98.0    9.0                         0.0              0.0              0.0
         15.0                        0.0              0.0              0.0
-97.0   -18.0                        0.0              0.0              0.0
        -10.0                        0.0              0.0              0.0
         16.0                        0.0              0.0              0.0

name_team_that_shot  Tampa Bay Lightning  Toronto Maple Leafs  \
x_coord y_coord
-98.0    9.0                         0.0                  0.0
         15.0                        0.0                  0.0
-97.0   -18.0                        0.0                  0.0
        -10.0                        0.0                  0.0
         16.0                        1.0                  0.0

name_team_that_shot  Vancouver Canucks  Washington Capitals  Winnipeg Jets
x_coord y_coord
-98.0    9.0                       0.0                  0.0            0.0
         15.0                      0.0                  0.0            0.0
-97.0   -18.0                      0.0                  0.0            0.0
        -10.0                      0.0                  0.0            0.0
         16.0                      0.0                  0.0            0.0

[5 rows x 30 columns]

In [255]:
df_count_game_per_team = df_20162017.groupby(['name_team_that_shot'])["id_game"].nunique().reset_index(name="count_game_per_team")
df_count_game_per_team.head(5)

  name_team_that_shot  count_game_per_team
0       Anaheim Ducks                   99
1     Arizona Coyotes                   82
2       Boston Bruins                   88
3      Buffalo Sabres                   82
4      Calgary Flames                   86

In [256]:
df_count_game_per_team[df_count_game_per_team["name_team_that_shot"]=="Boston Bruins"]["count_game_per_team"].values

array([88])

In [257]:
for team in df_question_3_p.columns :
    df_question_3_p[team] /= df_count_game_per_team[df_count_game_per_team["name_team_that_shot"]=="Boston Bruins"]["count_game_per_team"].values

In [259]:
df_question_3_p.head(5) # moyenne des tirs par heure pour chaque équipe

name_team_that_shot  Anaheim Ducks  Arizona Coyotes  Boston Bruins  \
x_coord y_coord
-98.0    9.0              0.000000              0.0            0.0
         15.0             0.011364              0.0            0.0
-97.0   -18.0             0.000000              0.0            0.0
        -10.0             0.000000              0.0            0.0
         16.0             0.000000              0.0            0.0

name_team_that_shot  Buffalo Sabres  Calgary Flames  Carolina Hurricanes  \
x_coord y_coord
-98.0    9.0                    0.0             0.0                  0.0
         15.0                   0.0             0.0                  0.0
-97.0   -18.0                   0.0             0.0                  0.0
        -10.0                   0.0             0.0                  0.0
         16.0                   0.0             0.0                  0.0

name_team_that_shot  Chicago Blackhawks  Colorado Avalanche  \
x_coord y_coord
-98.0    9.0                        0.0                 0.0
         15.0                       0.0                 0.0
-97.0   -18.0                       0.0                 0.0
        -10.0                       0.0                 0.0
         16.0                       0.0                 0.0

name_team_that_shot  Columbus Blue Jackets  Dallas Stars  ...  \
x_coord y_coord                                           ...
-98.0    9.0                           0.0      0.000000  ...
         15.0                          0.0      0.000000  ...
-97.0   -18.0                          0.0      0.011364  ...
        -10.0                          0.0      0.000000  ...
         16.0                          0.0      0.000000  ...

name_team_that_shot  Ottawa Senators  Philadelphia Flyers  \
x_coord y_coord
-98.0    9.0                     0.0                  0.0
         15.0                    0.0                  0.0
-97.0   -18.0                    0.0                  0.0
        -10.0                    0.0                  0.0
         16.0                    0.0                  0.0

name_team_that_shot  Pittsburgh Penguins  San Jose Sharks  St. Louis Blues  \
x_coord y_coord
-98.0    9.0                         0.0              0.0              0.0
         15.0                        0.0              0.0              0.0
-97.0   -18.0                        0.0              0.0              0.0
        -10.0                        0.0              0.0              0.0
         16.0                        0.0              0.0              0.0

name_team_that_shot  Tampa Bay Lightning  Toronto Maple Leafs  \
x_coord y_coord
-98.0    9.0                    0.000000                  0.0
         15.0                   0.000000                  0.0
-97.0   -18.0                   0.000000                  0.0
        -10.0                   0.000000                  0.0
         16.0                   0.011364                  0.0

name_team_that_shot  Vancouver Canucks  Washington Capitals  Winnipeg Jets
x_coord y_coord
-98.0    9.0                       0.0                  0.0            0.0
         15.0                      0.0                  0.0            0.0
-97.0   -18.0                      0.0                  0.0            0.0
        -10.0                      0.0                  0.0            0.0
         16.0                      0.0                  0.0            0.0

[5 rows x 30 columns]

In [268]:
len(df_question_2) == len(df_question_3_p)

True

In [270]:
df_question_2

       x_coord  y_coord  count  mean_shots_per_hour_in_whole_league
0        -98.0      9.0      2                             0.001519
1        -98.0     15.0      1                             0.000759
2        -97.0    -18.0      2                             0.001519
3        -97.0    -10.0      1                             0.000759
4        -97.0     16.0      1                             0.000759
...        ...      ...    ...                                  ...
11415     97.0     -8.0      1                             0.000759
11416     97.0     -7.0      1                             0.000759
11417     97.0      7.0      1                             0.000759
11418     97.0     10.0      1                             0.000759
11419     98.0     -3.0      1                             0.000759

[11420 rows x 4 columns]

In [271]:
df_question_2.query(f'x_coord == {-98.0	} and y_coord == {15.0}')["mean_shots_per_hour_in_whole_league"].values

array([0.0007593])

In [275]:
for x,y in  df_question_3_p.index:
    alpha = df_question_2.query(f'x_coord == {x} and y_coord == {y}')["mean_shots_per_hour_in_whole_league"].values
    df_question_3_p[(df_question_3_p.index.get_level_values('x_coord')==x) & (df_question_3_p.index.get_level_values('y_coord')==y)]=\
        df_question_3_p[(df_question_3_p.index.get_level_values('x_coord')==x) & (df_question_3_p.index.get_level_values('y_coord')==y)].apply(lambda x: x - alpha)
    #df_question_3[(df_question_3.index.get_level_values('x_coord')==x) & (df_question_3.index.get_level_values('y_coord')==y)][df_question_3.columns] - df_question_2.query(f'x_coord == {x} and y_coord == {y}')["mean"].values

In [ ]:
df_question_3_p

name_team_that_shot  Anaheim Ducks  Arizona Coyotes  Boston Bruins  \
x_coord y_coord
-98.0    9.0              0.000000              0.0            0.0
         15.0             0.011364              0.0            0.0
-97.0   -18.0             0.000000              0.0            0.0
        -10.0             0.000000              0.0            0.0
         16.0             0.000000              0.0            0.0
...                            ...              ...            ...
 97.0   -8.0              0.000000              0.0            0.0
        -7.0              0.000000              0.0            0.0
         7.0              0.000000              0.0            0.0
         10.0             0.000000              0.0            0.0
 98.0   -3.0              0.000000              0.0            0.0

name_team_that_shot  Buffalo Sabres  Calgary Flames  Carolina Hurricanes  \
x_coord y_coord
-98.0    9.0                    0.0             0.0                  0.0
         15.0                   0.0             0.0                  0.0
-97.0   -18.0                   0.0             0.0                  0.0
        -10.0                   0.0             0.0                  0.0
         16.0                   0.0             0.0                  0.0
...                             ...             ...                  ...
 97.0   -8.0                    0.0             0.0                  0.0
        -7.0                    0.0             0.0                  0.0
         7.0                    0.0             0.0                  0.0
         10.0                   0.0             0.0                  0.0
 98.0   -3.0                    0.0             0.0                  0.0

name_team_that_shot  Chicago Blackhawks  Colorado Avalanche  \
x_coord y_coord
-98.0    9.0                        0.0                 0.0
         15.0                       0.0                 0.0
-97.0   -18.0                       0.0                 0.0
        -10.0                       0.0                 0.0
         16.0                       0.0                 0.0
...                                 ...                 ...
 97.0   -8.0                        0.0                 0.0
        -7.0                        0.0                 0.0
         7.0                        0.0                 0.0
         10.0                       0.0                 0.0
 98.0   -3.0                        0.0                 0.0

name_team_that_shot  Columbus Blue Jackets  Dallas Stars  ...  \
x_coord y_coord                                           ...
-98.0    9.0                           0.0      0.000000  ...
         15.0                          0.0      0.000000  ...
-97.0   -18.0                          0.0      0.011364  ...
        -10.0                          0.0      0.000000  ...
         16.0                          0.0      0.000000  ...
...                                    ...           ...  ...
 97.0   -8.0                           0.0      0.000000  ...
        -7.0                           0.0      0.000000  ...
         7.0                           0.0      0.000000  ...
         10.0                          0.0      0.000000  ...
 98.0   -3.0                           0.0      0.000000  ...

name_team_that_shot  Ottawa Senators  Philadelphia Flyers  \
x_coord y_coord
-98.0    9.0                     0.0                  0.0
         15.0                    0.0                  0.0
-97.0   -18.0                    0.0                  0.0
        -10.0                    0.0                  0.0
         16.0                    0.0                  0.0
...                              ...                  ...
 97.0   -8.0                     0.0                  0.0
        -7.0                     0.0                  0.0
         7.0                     0.0                  0.0
         10.0                    0.0                  0.0
 98.0   -3.0                     0.0                  0.0

name_team_that_shot  Pittsburgh Penguins  San Jose Sharks  St. Louis Blues  \
x_coord y_coord
-98.0    9.0                         0.0              0.0              0.0
         15.0                        0.0              0.0              0.0
-97.0   -18.0                        0.0              0.0              0.0
        -10.0                        0.0              0.0              0.0
         16.0                        0.0              0.0              0.0
...                                  ...              ...              ...
 97.0   -8.0                         0.0              0.0              0.0
        -7.0                         0.0              0.0              0.0
         7.0                         0.0              0.0              0.0
         10.0                        0.0              0.0              0.0
 98.0   -3.0                         0.0              0.0              0.0

name_team_that_shot  Tampa Bay Lightning  Toronto Maple Leafs  \
x_coord y_coord
-98.0    9.0                    0.000000                  0.0
         15.0                   0.000000                  0.0
-97.0   -18.0                   0.000000                  0.0
        -10.0                   0.000000                  0.0
         16.0                   0.011364                  0.0
...                                  ...                  ...
 97.0   -8.0                    0.000000                  0.0
        -7.0                    0.000000                  0.0
         7.0                    0.000000                  0.0
         10.0                   0.000000                  0.0
 98.0   -3.0                    0.000000                  0.0

name_team_that_shot  Vancouver Canucks  Washington Capitals  Winnipeg Jets
x_coord y_coord
-98.0    9.0                       0.0                  0.0            0.0
         15.0                      0.0                  0.0            0.0
-97.0   -18.0                      0.0                  0.0            0.0
        -10.0                      0.0                  0.0            0.0
         16.0                      0.0                  0.0            0.0
...                                ...                  ...            ...
 97.0   -8.0                       0.0                  0.0            0.0
        -7.0                       0.0                  0.0            0.0
         7.0                       0.0                  0.0            0.0
         10.0                      0.0                  0.0            0.0
 98.0   -3.0                       0.0                  0.0            0.0

[11420 rows x 30 columns]

In [227]:
df_question_3_p.to_csv("../datasets/data_to_plot.csv", index=False)